export const FETCH_USER = 'FETCH_USER';
export const ASYNC_FETCH_USER = 'ASYNC_FETCH_USER';
export const FAIL_FETCH_USER = 'FAIL_FETCH_USER';



export const REMOVE_USER = "REMOVE_USER"
export const ASYNC_REMOVE_USER = "ASYNC_REMOVE_USER"
export const FAIL_REMOVE_USER = "FAIL_REMOVE_USER"



