export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_JOBS_FAILED = 'FETCH_JOBS_FAILED';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';

export const ADD_JOB = 'ADD_JOB';
export const ADD_JOB_FAILED = 'ADD_JOB_FAILED';
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS';

export const EDIT_JOB = 'EDIT_JOB';
export const EDIT_JOB_FAILED = 'EDIT_JOB_FAILED';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';

export const DELETE_JOB = 'DELETE_JOB';
export const DELETE_JOB_FAILED = 'DELETE_JOB_FAILED';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
