export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REGISTER_CANCELED = 'REGISTER_CANCELED';
export const SAVE_REGISTER_TOKEN = 'SAVE_REGISTER_TOKEN';
export const DELETE_REGISTER_TOKEN = 'DELETE_REGISTER_TOKEN';
export const LOGGED_OUT_REGISTER = 'LOGGED_OUT_REGISTER';
