export const CHANGE_USER_STAGE = "CHANGE_USER_STAGE"
export const ASYNC_CHANGE_USER_STAGE = "ASYNC_CHANGE_USER_STAGE"
export const FAIL_CHANGE_USER_STAGE = "FAIL_CHANGE_USER_STAGE"

export const FETCH_USER_STAGES = "FETCH_USER_STAGES"
export const ASYNC_FETCH_USER_STAGES = "ASYNC_FETCH_USER_STAGES"
export const FAIL_FETCH_USER_STAGES = "FAIL_FETCH_USER_STAGES"

export const UPDATE_USER_STAGE = "UPDATE_USER_STAGE"
export const ASYNC_UPDATE_USER_STAGE = "ASYNC_UPDATE_USER_STAGE"
export const FAIL_UPDATE_USER_STAGE = "FAIL_UPDATE_USER_STAGE"

export const CREATE_USER_STAGE = "CREATE_USER_STAGE"
export const ASYNC_CREATE_USER_STAGE = "ASYNC_CREATE_USER_STAGE"
export const FAIL_CREATE_USER_STAGE = "FAIL_CREATE_USER_STAGE"

export const REMOVE_USER_STAGE = "REMOVE_USER_STAGE"
export const ASYNC_REMOVE_USER_STAGE = "ASYNC_REMOVE_USER_STAGE"
export const FAIL_REMOVE_USER_STAGE = "FAIL_REMOVE_USER_STAGE"

export const CHANGE_ORDER_OF_USER_STAGE = "CHANGE_ORDER_OF_USER_STAGE"
export const ASYNC_CHANGE_ORDER_OF_USER_STAGE = "ASYNC_CHANGE_ORDER_OF_USER_STAGE"
export const FAIL_CHANGE_ORDER_OF_USER_STAGE = "FAIL_CHANGE_ORDER_OF_USER_STAGE"

export const FETCH_USERS = "FETCH_USERS"
export const ASYNC_FETCH_USERS = "ASYNC_FETCH_USERS"
export const FAIL_FETCH_USERS = "FAIL_FETCH_USERS"